### ISSUE TITLE
upgrade to Go 1.21 or 1.22

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-showcase#1502]
No real reason to be behind the times on Go version in this repo. It will probably require an update in gapic-generator-go in order to run the integration tests from the released showcase version if we start using newer stdlb packages, but that's not too bad either.

**Comment by quartzmo** [comment]
@julieqiu @codyoss,

I think the Go client libraries team needs to request a short-term downgrade to `1.21`.

#1533 upgraded the Go version in this repo to `1.23`. However, in order to enable the Go client libraries to continue testing our current min version (`1.21`), the Go version in this repo also needs to support `1.21`.

This is because the test code in gapic-generator-go imports packages from gapic-showcase (example: [echo_test.go](https://github.com/googleapis/gapic-generator-go/blob/main/showcase/echo_test.go#L30-L31)). @codyoss and I have discussed decoupling gapic-generator-go testing from gapic-showcase packages, but we need some time to do it.
