### ISSUE TITLE
Consider adding a dummy LRO service

### ISSUE THREAD

**Issue by jbolinger** [googleapis/gapic-showcase#180]
Can we add a simple service that implements [operations.proto](https://github.com/googleapis/googleapis/blob/master/google/longrunning/operations.proto) as an optional part of showcase (not in echo). It doesn't need to actually manage operations but we'd like it to be available so we can exercise the generated helper methods for accessing these methods.

See https://github.com/googleapis/gapic-generator-ruby/issues/132 for more context.

**Comment by noahdietz** [comment]
Turns out we already have an  `longrunning.OperationsService` [implementation](https://github.com/googleapis/gapic-showcase/blob/4e9247b654f52994586eb256514c98d45d1d3d4b/server/services/operations_service.go), just that only 1/5 methods is implmented and that 1 method (`GetOperation`) handles `EchoService.Wait` and `MessagingService.SearchBlurbs`

So we should implement the other methods, but it might need to be done in the context of these services we have already i.e. `EchoService`. Start a `Wait` RPC, run ListOperations (lists the echo service Wait ops), run CancelOperation on a Wait op, etc.

**Comment by jbolinger** [comment]
I don't think the service needs to actually manage operations to be useful. For example, if we changed the implementation to return some fixed data that would be enough (and maybe error out on a well known input value).

We could start there and add more if somebody wants it?

**Comment by noahdietz** [comment]
Ok, that's fine I guess.
