### ISSUE TITLE
send back trailing metadata in server code for server streaming rpcs

### ISSUE THREAD

**Issue by arithmetic1728** [googleapis/gapic-showcase#278]
We (https://github.com/googleapis/gapic-generator-python) are using gapic-showcase server for system testing. It would be great to have the server sending back some trailing metadata for server streaming rpcs, like "expand" and "chat" rpc is echo service.

**Comment by noahdietz** [comment]
Turns out this was already implemented in #194! The Expand, Chat, and Collect RPCs all echo the `showcase-trailer` metadata provided in the initial request's metadata as Trailing Metadata. 

So in the streaming requests, include some metadata keyed with `showcase-trailer` and expect it on the response.
